import "@repo/ui/styles/shared-globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { auth } from "../auth";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en" className={inter.className}>
        <body>{children}</body>
      </html>
    </SessionProvider>
  );
}
